package ams.entity;
// Generated Jul 4, 2013 2:24:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblDosen generated by hbm2java
 */
@Entity
@Table(name="tbl_dosen"
    ,catalog="ams_db"
)
public class TblDosen  implements java.io.Serializable {


     private Integer idDosen;
     private TblJurusan tblJurusan;
     private String nip;
     private String namaDosen;
     private String tempatLahir;
     private Date tglLahir;
     private String jenisKelamin;
     private String pendidikan;
     private String gelar;
     private String noKartu;
     private Set tblJadwals = new HashSet(0);

    public TblDosen() {
    }

	
    public TblDosen(TblJurusan tblJurusan, String nip, String namaDosen, String tempatLahir, Date tglLahir, String jenisKelamin, String pendidikan, String gelar) {
        this.tblJurusan = tblJurusan;
        this.nip = nip;
        this.namaDosen = namaDosen;
        this.tempatLahir = tempatLahir;
        this.tglLahir = tglLahir;
        this.jenisKelamin = jenisKelamin;
        this.pendidikan = pendidikan;
        this.gelar = gelar;
    }
    public TblDosen(TblJurusan tblJurusan, String nip, String namaDosen, String tempatLahir, Date tglLahir, String jenisKelamin, String pendidikan, String gelar, String noKartu, Set tblJadwals) {
       this.tblJurusan = tblJurusan;
       this.nip = nip;
       this.namaDosen = namaDosen;
       this.tempatLahir = tempatLahir;
       this.tglLahir = tglLahir;
       this.jenisKelamin = jenisKelamin;
       this.pendidikan = pendidikan;
       this.gelar = gelar;
       this.noKartu = noKartu;
       this.tblJadwals = tblJadwals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_dosen", unique=true, nullable=false)
    public Integer getIdDosen() {
        return this.idDosen;
    }
    
    public void setIdDosen(Integer idDosen) {
        this.idDosen = idDosen;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_jurusan", nullable=false)
    public TblJurusan getTblJurusan() {
        return this.tblJurusan;
    }
    
    public void setTblJurusan(TblJurusan tblJurusan) {
        this.tblJurusan = tblJurusan;
    }
    
    @Column(name="nip", nullable=false, length=20)
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }
    
    @Column(name="nama_dosen", nullable=false)
    public String getNamaDosen() {
        return this.namaDosen;
    }
    
    public void setNamaDosen(String namaDosen) {
        this.namaDosen = namaDosen;
    }
    
    @Column(name="tempat_lahir", nullable=false, length=30)
    public String getTempatLahir() {
        return this.tempatLahir;
    }
    
    public void setTempatLahir(String tempatLahir) {
        this.tempatLahir = tempatLahir;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="tgl_lahir", nullable=false, length=10)
    public Date getTglLahir() {
        return this.tglLahir;
    }
    
    public void setTglLahir(Date tglLahir) {
        this.tglLahir = tglLahir;
    }
    
    @Column(name="jenis_kelamin", nullable=false)
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    
    @Column(name="pendidikan", nullable=false, length=10)
    public String getPendidikan() {
        return this.pendidikan;
    }
    
    public void setPendidikan(String pendidikan) {
        this.pendidikan = pendidikan;
    }
    
    @Column(name="gelar", nullable=false, length=10)
    public String getGelar() {
        return this.gelar;
    }
    
    public void setGelar(String gelar) {
        this.gelar = gelar;
    }
    
    @Column(name="no_kartu", length=10)
    public String getNoKartu() {
        return this.noKartu;
    }
    
    public void setNoKartu(String noKartu) {
        this.noKartu = noKartu;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblDosen")
    public Set getTblJadwals() {
        return this.tblJadwals;
    }
    
    public void setTblJadwals(Set tblJadwals) {
        this.tblJadwals = tblJadwals;
    }




}


