package ams.entity;
// Generated Jul 4, 2013 2:24:47 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblFakultas generated by hbm2java
 */
@Entity
@Table(name = "tbl_fakultas", catalog = "ams_db")
public class TblFakultas implements java.io.Serializable {

    private int idFakultas;
    private String fakultas;
    private Set tblJurusans = new HashSet(0);

    public TblFakultas() {
    }

    public TblFakultas(int idFakultas, String fakultas) {
        this.idFakultas = idFakultas;
        this.fakultas = fakultas;
    }

    public TblFakultas(int idFakultas, String fakultas, Set tblJurusans) {
        this.idFakultas = idFakultas;
        this.fakultas = fakultas;
        this.tblJurusans = tblJurusans;
    }

    @Id
    @Column(name = "id_fakultas", unique = true, nullable = false)
    public int getIdFakultas() {
        return this.idFakultas;
    }

    public void setIdFakultas(int idFakultas) {
        this.idFakultas = idFakultas;
    }

    @Column(name = "fakultas", nullable = false, length = 50)
    public String getFakultas() {
        return this.fakultas;
    }

    public void setFakultas(String fakultas) {
        this.fakultas = fakultas;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tblFakultas")
    public Set getTblJurusans() {
        return this.tblJurusans;
    }

    public void setTblJurusans(Set tblJurusans) {
        this.tblJurusans = tblJurusans;
    }
}
