package ams.entity;
// Generated Jul 4, 2013 2:24:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblJadwal generated by hbm2java
 */
@Entity
@Table(name="tbl_jadwal"
    ,catalog="ams_db"
)
public class TblJadwal  implements java.io.Serializable {


     private Integer idJadwal;
     private TblMakul tblMakul;
     private TblJurusan tblJurusan;
     private TblRuangan tblRuangan;
     private TblKelas tblKelas;
     private TblDosen tblDosen;
     private int hari;
     private Date jamMulai;
     private Date jamSelesai;
     private Set tblAbsens = new HashSet(0);

    public TblJadwal() {
    }

	
    public TblJadwal(TblMakul tblMakul, TblJurusan tblJurusan, TblRuangan tblRuangan, TblKelas tblKelas, TblDosen tblDosen, int hari, Date jamMulai, Date jamSelesai) {
        this.tblMakul = tblMakul;
        this.tblJurusan = tblJurusan;
        this.tblRuangan = tblRuangan;
        this.tblKelas = tblKelas;
        this.tblDosen = tblDosen;
        this.hari = hari;
        this.jamMulai = jamMulai;
        this.jamSelesai = jamSelesai;
    }
    public TblJadwal(TblMakul tblMakul, TblJurusan tblJurusan, TblRuangan tblRuangan, TblKelas tblKelas, TblDosen tblDosen, int hari, Date jamMulai, Date jamSelesai, Set tblAbsens) {
       this.tblMakul = tblMakul;
       this.tblJurusan = tblJurusan;
       this.tblRuangan = tblRuangan;
       this.tblKelas = tblKelas;
       this.tblDosen = tblDosen;
       this.hari = hari;
       this.jamMulai = jamMulai;
       this.jamSelesai = jamSelesai;
       this.tblAbsens = tblAbsens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_jadwal", unique=true, nullable=false)
    public Integer getIdJadwal() {
        return this.idJadwal;
    }
    
    public void setIdJadwal(Integer idJadwal) {
        this.idJadwal = idJadwal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_makul", nullable=false)
    public TblMakul getTblMakul() {
        return this.tblMakul;
    }
    
    public void setTblMakul(TblMakul tblMakul) {
        this.tblMakul = tblMakul;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_jurusan", nullable=false)
    public TblJurusan getTblJurusan() {
        return this.tblJurusan;
    }
    
    public void setTblJurusan(TblJurusan tblJurusan) {
        this.tblJurusan = tblJurusan;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ruangan", nullable=false)
    public TblRuangan getTblRuangan() {
        return this.tblRuangan;
    }
    
    public void setTblRuangan(TblRuangan tblRuangan) {
        this.tblRuangan = tblRuangan;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_kelas", nullable=false)
    public TblKelas getTblKelas() {
        return this.tblKelas;
    }
    
    public void setTblKelas(TblKelas tblKelas) {
        this.tblKelas = tblKelas;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_dosen", nullable=false)
    public TblDosen getTblDosen() {
        return this.tblDosen;
    }
    
    public void setTblDosen(TblDosen tblDosen) {
        this.tblDosen = tblDosen;
    }
    
    @Column(name="hari", nullable=false)
    public int getHari() {
        return this.hari;
    }
    
    public void setHari(int hari) {
        this.hari = hari;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="jam_mulai", nullable=false, length=8)
    public Date getJamMulai() {
        return this.jamMulai;
    }
    
    public void setJamMulai(Date jamMulai) {
        this.jamMulai = jamMulai;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="jam_selesai", nullable=false, length=8)
    public Date getJamSelesai() {
        return this.jamSelesai;
    }
    
    public void setJamSelesai(Date jamSelesai) {
        this.jamSelesai = jamSelesai;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblJadwal")
    public Set getTblAbsens() {
        return this.tblAbsens;
    }
    
    public void setTblAbsens(Set tblAbsens) {
        this.tblAbsens = tblAbsens;
    }




}


