package ams.entity;
// Generated Jul 4, 2013 2:24:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblMakul generated by hbm2java
 */
@Entity
@Table(name="tbl_makul"
    ,catalog="ams_db"
)
public class TblMakul  implements java.io.Serializable {


     private String idMakul;
     private TblJurusan tblJurusan;
     private String mataKuliah;
     private Set tblJadwals = new HashSet(0);

    public TblMakul() {
    }

	
    public TblMakul(String idMakul, TblJurusan tblJurusan, String mataKuliah) {
        this.idMakul = idMakul;
        this.tblJurusan = tblJurusan;
        this.mataKuliah = mataKuliah;
    }
    public TblMakul(String idMakul, TblJurusan tblJurusan, String mataKuliah, Set tblJadwals) {
       this.idMakul = idMakul;
       this.tblJurusan = tblJurusan;
       this.mataKuliah = mataKuliah;
       this.tblJadwals = tblJadwals;
    }
   
     @Id 
    
    @Column(name="id_makul", unique=true, nullable=false, length=15)
    public String getIdMakul() {
        return this.idMakul;
    }
    
    public void setIdMakul(String idMakul) {
        this.idMakul = idMakul;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_jurusan", nullable=false)
    public TblJurusan getTblJurusan() {
        return this.tblJurusan;
    }
    
    public void setTblJurusan(TblJurusan tblJurusan) {
        this.tblJurusan = tblJurusan;
    }
    
    @Column(name="mata_kuliah", nullable=false, length=50)
    public String getMataKuliah() {
        return this.mataKuliah;
    }
    
    public void setMataKuliah(String mataKuliah) {
        this.mataKuliah = mataKuliah;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblMakul")
    public Set getTblJadwals() {
        return this.tblJadwals;
    }
    
    public void setTblJadwals(Set tblJadwals) {
        this.tblJadwals = tblJadwals;
    }




}


