package ams.entity;
// Generated Jul 4, 2013 2:24:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblRuangan generated by hbm2java
 */
@Entity
@Table(name="tbl_ruangan"
    ,catalog="ams_db"
)
public class TblRuangan  implements java.io.Serializable {


     private Integer idRuangan;
     private String namaRuangan;
     private int lantai;
     private Set tblJadwals = new HashSet(0);

    public TblRuangan() {
    }

	
    public TblRuangan(String namaRuangan, int lantai) {
        this.namaRuangan = namaRuangan;
        this.lantai = lantai;
    }
    public TblRuangan(String namaRuangan, int lantai, Set tblJadwals) {
       this.namaRuangan = namaRuangan;
       this.lantai = lantai;
       this.tblJadwals = tblJadwals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_ruangan", unique=true, nullable=false)
    public Integer getIdRuangan() {
        return this.idRuangan;
    }
    
    public void setIdRuangan(Integer idRuangan) {
        this.idRuangan = idRuangan;
    }
    
    @Column(name="nama_ruangan", nullable=false, length=10)
    public String getNamaRuangan() {
        return this.namaRuangan;
    }
    
    public void setNamaRuangan(String namaRuangan) {
        this.namaRuangan = namaRuangan;
    }
    
    @Column(name="lantai", nullable=false)
    public int getLantai() {
        return this.lantai;
    }
    
    public void setLantai(int lantai) {
        this.lantai = lantai;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblRuangan")
    public Set getTblJadwals() {
        return this.tblJadwals;
    }
    
    public void setTblJadwals(Set tblJadwals) {
        this.tblJadwals = tblJadwals;
    }




}


