package ams.entity;
// Generated Jul 4, 2013 2:24:47 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblUser generated by hbm2java
 */
@Entity
@Table(name="tbl_user"
    ,catalog="ams_db"
)
public class TblUser  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;
     private String namaUser;
     private String hakAkses;

    public TblUser() {
    }

    public TblUser(String username, String password, String namaUser, String hakAkses) {
       this.username = username;
       this.password = password;
       this.namaUser = namaUser;
       this.hakAkses = hakAkses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_user", unique=true, nullable=false)
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="username", nullable=false, length=10)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", nullable=false, length=10)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="nama_user", nullable=false, length=30)
    public String getNamaUser() {
        return this.namaUser;
    }
    
    public void setNamaUser(String namaUser) {
        this.namaUser = namaUser;
    }
    
    @Column(name="hak_akses", nullable=false, length=10)
    public String getHakAkses() {
        return this.hakAkses;
    }
    
    public void setHakAkses(String hakAkses) {
        this.hakAkses = hakAkses;
    }




}


