/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ams.gui;

import ams.dao.TblAbsenDao;
import ams.dao.TblDosenDao;
import ams.dao.TblFakultasDao;
import ams.dao.TblJurusanDao;
import ams.entity.TblAbsen;
import ams.entity.TblDosen;
import ams.entity.TblFakultas;
import ams.entity.TblJurusan;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bayu
 */
public class AbsenPanel extends javax.swing.JPanel {

    /**
     * Creates new form AbsenPanel
     */
    TblAbsenDao absendao = new TblAbsenDao();
    TblFakultasDao fakdao = new TblFakultasDao();
    TblJurusanDao jurdao = new TblJurusanDao();
    TblDosenDao dosendao = new TblDosenDao();

    public AbsenPanel() {
        initComponents();
        initFakultas();
        //initJurusan();
        //initDosen();
        displayResult(absendao.getAllAbsen());
    }

    private void displayResult(List resultList) {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Fakultas");
        tableHeaders.add("Jurusan");
        tableHeaders.add("Dosen");
        tableHeaders.add("Mata Kuliah");
        tableHeaders.add("Kelas");
        tableHeaders.add("Ruangan");
        tableHeaders.add("Jam Mulai");
        tableHeaders.add("Jam Selesai");
        tableHeaders.add("Absen Masuk");
        tableHeaders.add("Absen Keluar");
        //tableHeaders.add("Operation");

        Iterator its = resultList.iterator();
        while (its.hasNext()) {
            TblAbsen data = (TblAbsen) its.next();
            Vector<Object> oneRow = new Vector<Object>();
//            oneRow.add(data.getIdAbsen());
//            oneRow.add(data.getAbsenMulai());
//            oneRow.add(data.getAbsenSelesai());
            oneRow.add(data.getTblJadwal().getTblJurusan().getTblFakultas().getFakultas());
            oneRow.add(data.getTblJadwal().getTblJurusan().getJurusan());
            oneRow.add(data.getTblJadwal().getTblDosen().getNamaDosen());
            oneRow.add(data.getTblJadwal().getTblMakul().getMataKuliah());
            oneRow.add(data.getTblJadwal().getTblKelas().getKelas());
            oneRow.add(data.getTblJadwal().getTblRuangan().getNamaRuangan());
            oneRow.add(data.getTblJadwal().getJamMulai());
            oneRow.add(data.getTblJadwal().getJamSelesai());
            oneRow.add(data.getAbsenMulai());
            oneRow.add(data.getAbsenSelesai());
            //System.out.println(str[0] + str[1] + str[2]);
            tableData.add(oneRow);
        }
        resultTable.setModel(new DefaultTableModel(tableData, tableHeaders) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    public void initFakultas() {
        cmbFakultas.removeAllItems();
        Iterator it = fakdao.getAllFakultas().iterator();
        while (it.hasNext()) {
            TblFakultas data = (TblFakultas) it.next();
            cmbFakultas.addItem(data.getFakultas());
        }
    }

    public void initJurusan(String fak) {
        cmbJurusan.removeAllItems();
        Iterator it = jurdao.getJurusanByFak(fak).iterator();
        while (it.hasNext()) {
            TblJurusan data = (TblJurusan) it.next();
            cmbJurusan.addItem(data.getJurusan());
        }
    }

    public void initDosen(String jur) {
        cmbDosen.removeAllItems();
        Iterator it = dosendao.getDosenByJur(jur).iterator();
        while (it.hasNext()) {
            TblDosen data = (TblDosen) it.next();
            cmbDosen.addItem(data.getNamaDosen());
        }
    }

    public void Refresh() {
        displayResult(absendao.getAllAbsen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbFakultas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbJurusan = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbDosen = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        tglAwal = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        tglAkhir = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Fakultas");

        cmbFakultas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFakultas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFakultasItemStateChanged(evt);
            }
        });

        jLabel2.setText("Jurusan");

        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbJurusan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbJurusanItemStateChanged(evt);
            }
        });

        jLabel4.setText("Dosen");

        cmbDosen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Tanggal");

        jLabel7.setText("Sampai");

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultTable);

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmbFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbDosen, cmbFakultas, cmbJurusan});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tglAkhir, tglAwal});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(tglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(369, 369, 369))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbDosen, cmbFakultas, cmbJurusan, jButton1, jLabel7, tglAkhir, tglAwal});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tglAwal.getDate() != null || tglAkhir.getDate() != null) {
            Date mulai = tglAwal.getDate();
            Date selesai = tglAkhir.getDate();
            if (cmbFakultas.getSelectedItem() != -1) {
                if (cmbJurusan.getSelectedItem() != -1) {
                    if (cmbDosen.getSelectedItem() != -1) {
                        String fak = cmbFakultas.getSelectedItem().toString();
                        String jur = cmbJurusan.getSelectedItem().toString();
                        String dos = cmbDosen.getSelectedItem().toString();
                        displayResult(absendao.getCariAbsen(fak, jur, dos, mulai, selesai));
                    } else {
                        JOptionPane.showMessageDialog(this, "Pilihan Dosen Kosong", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Pilihan Jurusan Kosong", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilihan Fakultas Kosong", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tanggal Awal Atau Tanggal Akhir Kosong", "Warning", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbFakultasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFakultasItemStateChanged
        // TODO add your handling code here:
        if (cmbFakultas.getSelectedIndex() != -1) {
            initJurusan(cmbFakultas.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbFakultasItemStateChanged

    private void cmbJurusanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbJurusanItemStateChanged
        // TODO add your handling code here:
        if (cmbJurusan.getSelectedIndex() != -1) {
            initDosen(cmbJurusan.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbJurusanItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDosen;
    private javax.swing.JComboBox cmbFakultas;
    private javax.swing.JComboBox cmbJurusan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultTable;
    private com.toedter.calendar.JDateChooser tglAkhir;
    private com.toedter.calendar.JDateChooser tglAwal;
    // End of variables declaration//GEN-END:variables
}
