/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ams.gui;

import ams.dao.TblDosenDao;
import ams.entity.TblDosen;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bayu
 */
public class DosenPanel extends javax.swing.JPanel {
     private static WindowListener closeWindow = new WindowAdapter() {
         public void windowClosing(WindowEvent e) {
             e.getWindow().dispose();
         }
     };
    /**
     * Creates new form DosenPanel
     */
    TblDosenDao dosendao = new TblDosenDao();

    public DosenPanel() {
        initComponents();
        displayResult(dosendao.getAllDosen());
        //resultTable.isCellEditable(WIDTH, WIDTH);
    }

    private void displayResult(List resultList) {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("ID Dosen");
        tableHeaders.add("NIP");
        tableHeaders.add("Nama Dosen");
        tableHeaders.add("Tempat Lahir");
        tableHeaders.add("Tanggal Lahir");
        tableHeaders.add("Jenis Kelamin");
        tableHeaders.add("Pendidikan");
        tableHeaders.add("Gelar");
        tableHeaders.add("No Kartu");
        //tableHeaders.add("Operation");

        for (Object o : resultList) {
            TblDosen dosen = (TblDosen) o;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(dosen.getIdDosen());
            oneRow.add(dosen.getNip());
            oneRow.add(dosen.getNamaDosen());
            oneRow.add(dosen.getTempatLahir());
            oneRow.add(showDateNow(dosen.getTglLahir()));
            oneRow.add(dosen.getJenisKelamin());
            oneRow.add(dosen.getPendidikan());
            oneRow.add(dosen.getGelar());
            oneRow.add(dosen.getNoKartu());
            //oneRow.add("Update || Delete");
            tableData.add(oneRow);
        }
        resultTable.setModel(new DefaultTableModel(tableData, tableHeaders) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }
    

    public String showDateNow(Date tgl) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String hasil = sdf.format(tgl);
        return hasil;
    }

    public void Refresh() {
        displayResult(dosendao.getAllDosen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultTable);

        txtCari.setToolTipText("Cari Mata Kuliah");
        txtCari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCariCaretUpdate(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Cari Nama Dosen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCari)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1)))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int rowindex = resultTable.convertRowIndexToModel(resultTable.getSelectedRow());
        //System.out.println(resultTable.getValueAt(rowindex, 0));
        //System.out.println(rowindex);
        if (rowindex != -1) {
            TblDosen test = dosendao.getDosenById(Integer.parseInt(resultTable.getValueAt(rowindex, 0).toString()));
            DosenOperation in = new DosenOperation(test);
//            in.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Yang Ingin Diupdate", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DosenOperation in = new DosenOperation(null);
//        JDialog a = new JDialog(new FormUtama(),"Test",JDialog.ModalityType.APPLICATION_MODAL);
//        a.add(in);
//        a.validate();
//        a.pack();
//        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCariCaretUpdate
        // TODO add your handling code here:
        //System.out.println("test");
        displayResult(dosendao.getCariDosen(txtCari.getText()));
        //makuldao.getCariMakul(txtCari.getText());
    }//GEN-LAST:event_txtCariCaretUpdate

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int rowindex = resultTable.convertRowIndexToModel(resultTable.getSelectedRow());
        if (rowindex != -1) {
            int a = JOptionPane.showConfirmDialog(this, "Yakin Data Ini Ingin Dihapus? ", "Delete", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                TblDosen test = dosendao.getDosenById(Integer.parseInt(resultTable.getValueAt(rowindex, 0).toString()));
                dosendao.deleteDosen(test.getIdDosen());
                Refresh();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Yang Ingin Didelete", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable resultTable;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
