/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ams.gui;

import ams.dao.TblFakultasDao;
import ams.entity.TblFakultas;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Bayu
 */
public class FakultasOperation extends javax.swing.JPanel {

    TblFakultas fakultas;
    JDialog a = new JDialog(new FormUtama(),"Manage Fakultas",JDialog.ModalityType.APPLICATION_MODAL);
    
    public FakultasOperation(TblFakultas fakultas) {
        initComponents();
        initUpdateFakultas(fakultas);
        
        a.add(this);
        a.validate();
        a.pack();
        a.setVisible(true);
    }
    private void initUpdateFakultas(TblFakultas fakultas){
        this.fakultas = fakultas;
        if (fakultas != null) {
            txtIdFakultas.setText(new Integer(fakultas.getIdFakultas()).toString());
            txtFakultas.setText(fakultas.getFakultas());
            txtIdFakultas.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtFakultas = new javax.swing.JTextField();
        txtIdFakultas = new javax.swing.JTextField();

        jLabel2.setText("Id Fakultas");

        jLabel3.setText("Fakultas");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdFakultas, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(txtFakultas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String idfakultas;
            String namafakultas;

            idfakultas = txtIdFakultas.getText();
            namafakultas = txtFakultas.getText();

            if (idfakultas.equals("") || namafakultas.equals("")) {
                JOptionPane.showMessageDialog(this, "Pastikan Inputan Yang Anda Masukan Benar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                TblFakultas fk = new TblFakultas();
                fk.setIdFakultas(Integer.parseInt(idfakultas));
                fk.setFakultas(namafakultas);

                int confirm = JOptionPane.showConfirmDialog(this, "Yakin Data Ini Ingin Disimpan?", "Simpan Data", JOptionPane.OK_CANCEL_OPTION);
                if (confirm == JOptionPane.OK_OPTION) {
                    TblFakultasDao fakultasdao = new TblFakultasDao();
                    if (this.fakultas != null) {
                        fakultas.setIdFakultas(this.fakultas.getIdFakultas());
                        fakultasdao.updateFakultas(fk);
                        JOptionPane.showMessageDialog(this, "Data Telah Berhasil Diupdate", "Update", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        fakultasdao.addFakultas(fk);
                        JOptionPane.showMessageDialog(this, "Data Telah Berhasil Diinput", "Insert", JOptionPane.INFORMATION_MESSAGE);
                    }
                    //makuldao.addMakul(makul);
                    //JOptionPane.showMessageDialog(this, "Data Telah Berhasil Diinput", "Insert Makul", JOptionPane.INFORMATION_MESSAGE);
                    a.dispose();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pastikan Inputan Yang Anda Masukan Benar", "Error", JOptionPane.ERROR_MESSAGE);
        }
//        ManageFakultasGui fkgui = new ManageFakultasGui();
//        fkgui.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFakultas;
    private javax.swing.JTextField txtIdFakultas;
    // End of variables declaration//GEN-END:variables
}
