/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ams.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;

/**
 *
 * @author Bayu
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    AbsenPanel absen = new AbsenPanel();
    JadwalPanel jadwal = new JadwalPanel();
    DosenPanel dosen = new DosenPanel();
    MakulPanel makul = new MakulPanel();
    FakultasPanel fak = new FakultasPanel();
    RuanganPanel ruang = new RuanganPanel();
    JurusanPanel jurusan = new JurusanPanel();
    KelasPanel kelas = new KelasPanel();
    UserPanel user = new UserPanel();
    ReportPanel report = new ReportPanel();
    JTabbedPane setting = new JTabbedPane();
    public FormUtama() {
        initComponents();
        ImageIcon img = new ImageIcon(getClass().getResource("images/ams_transfaran3.png"));
        this.setIconImage(img.getImage());
        this.setExtendedState(MAXIMIZED_BOTH);
//        makeFrameFullSize(this);
        ImageIcon homeicon = createImageIcon("images/home.png");
        ImageIcon reporticon = createImageIcon("images/reporting.png");
        ImageIcon settingicon = createImageIcon("images/setting.png");
        ImageIcon absenicon = createImageIcon("images/dosen.png");
        ImageIcon dosenicon = createImageIcon("images/dosen.png");
        ImageIcon fakultasicon = createImageIcon("images/fakultas.png");
        ImageIcon jadwalicon = createImageIcon("images/jadwal.png");
        ImageIcon jurusanicon = createImageIcon("images/jurusan.png");
        ImageIcon kelasicon = createImageIcon("images/kelas.png");
        ImageIcon matakuliahicon = createImageIcon("images/matakuliah.png");
        ImageIcon ruangicon = createImageIcon("images/ruang.png");
        ImageIcon usericon = createImageIcon("images/user.png");
//        System.out.println(setting.getTabPlacement());
        //setting.setTabPlacement(2);
        setting.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane4.addTab("",homeicon, absen);
        jTabbedPane4.addTab("",reporticon, report);
        jTabbedPane4.addTab("",settingicon, setting);
        setting.addTab("",jadwalicon,jadwal);
        setting.addTab("",dosenicon,dosen);
        setting.addTab("",matakuliahicon,makul);
        setting.addTab("",ruangicon,ruang);
        setting.addTab("",fakultasicon,fak);
        setting.addTab("",jurusanicon,jurusan);
        setting.addTab("",kelasicon,kelas);
        setting.addTab("",usericon,user);
    }
    
    private void makeFrameFullSize(JFrame aFrame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        aFrame.setSize(screenSize.width, screenSize.height);
    }
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = FormUtama.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
    
    public void Refresh(){
        jadwal.Refresh();
        dosen.Refresh();
        makul.Refresh();
        ruang.Refresh();
        fak.Refresh();
        jurusan.Refresh();
        kelas.Refresh();
        user.Refresh();
        jTabbedPane4.updateUI();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Attendance Management System");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTabbedPane4.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        System.out.println("test");
        Refresh();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                UIManager.put("swing.boldMetal",Boolean.FALSE);
                new FormUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables
}
