/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ams.gui;

import ams.dao.TblJadwalDao;
import ams.entity.TblJadwal;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bayu
 */
public class JadwalPanel extends javax.swing.JPanel {

    /**
     * Creates new form JadwalPanel
     */
    TblJadwalDao jadwaldao = new TblJadwalDao();
    String[] hari = {"Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"};

    public JadwalPanel() {
        initComponents();
        displayResult(jadwaldao.getAllJadwal());
    }

    private void displayResult(List resultList) {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("ID Jadwal");
        tableHeaders.add("ID Dosen");
        tableHeaders.add("ID Mata Kuliah");
        tableHeaders.add("ID Kelas");
        tableHeaders.add("Hari");
        tableHeaders.add("Jam Mulai");
        tableHeaders.add("Jam Selesai");
        tableHeaders.add("Ruangan");
        tableHeaders.add("Jurusan");
        //tableHeaders.add("Operation");

        Iterator its = resultList.iterator();
        while (its.hasNext()) {
            TblJadwal data = (TblJadwal) its.next();
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(data.getIdJadwal());
            oneRow.add(data.getTblDosen().getNamaDosen());
            oneRow.add(data.getTblMakul().getMataKuliah());
            oneRow.add(data.getTblKelas().getKelas());
            oneRow.add(hari[data.getHari() - 1]);
            oneRow.add(data.getJamMulai());
            oneRow.add(data.getJamSelesai());
            oneRow.add(data.getTblRuangan().getNamaRuangan());
            oneRow.add(data.getTblJurusan().getJurusan());
            //System.out.println(str[0] + str[1] + str[2]);
            //System.out.println(data.getJamMulai().getTime());
            tableData.add(oneRow);
        }
        resultTable.setModel(new DefaultTableModel(tableData, tableHeaders) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    public void Refresh() {
        displayResult(jadwaldao.getAllJadwal());
    }
    
//    public void initCmboCari(){
//        cmbCari.removeAllItems();
//        cmbCari.addItem("Mata Kuliah");
//        cmbCari.addItem("Dosen");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        txtCari.setToolTipText("Cari Mata Kuliah");
        txtCari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCariCaretUpdate(evt);
            }
        });

        jLabel2.setText("Cari");

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultTable);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCariCaretUpdate
        // TODO add your handling code here:
        //System.out.println("test");
        displayResult(jadwaldao.getCariJadwal(txtCari.getText()));
        //makuldao.getCariMakul(txtCari.getText());
    }//GEN-LAST:event_txtCariCaretUpdate

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int rowindex = resultTable.convertRowIndexToModel(resultTable.getSelectedRow());
        //System.out.println(resultTable.getValueAt(rowindex, 0));
        //System.out.println(rowindex);
        if (rowindex != -1) {
            TblJadwal test = jadwaldao.getJadwalById(Integer.parseInt(resultTable.getValueAt(rowindex, 0).toString()));
            JadwalOperation in = new JadwalOperation(test);
//            in.setVisible(true);
            //this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Yang Ingin Diupdate", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int rowindex = resultTable.convertRowIndexToModel(resultTable.getSelectedRow());
        if (rowindex != -1) {
            int a = JOptionPane.showConfirmDialog(this, "Yakin Data Ini Ingin Dihapus? ", "Delete", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                TblJadwal test = jadwaldao.getJadwalById(Integer.parseInt(resultTable.getValueAt(rowindex, 0).toString()));
                jadwaldao.deleteJadwal(test.getIdJadwal());
                Refresh();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Yang Ingin Didelete", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JadwalOperation in = new JadwalOperation(null);
//        in.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable resultTable;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
