/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ams.gui;

import ams.dao.*;
import ams.entity.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Bayu
 */
public class JadwalOperation extends javax.swing.JPanel {

    /**
     * Creates new form PanelJadwalOperation
     */
    TblJadwal jadwal;
    TblJadwalDao jaddao = new TblJadwalDao();
    JDialog a = new JDialog(new FormUtama(), "Manage Jadwal", JDialog.ModalityType.APPLICATION_MODAL);

    public JadwalOperation(TblJadwal jadwal) {
        initComponents();
        initCmbHari();
        initCmbDosen();
        initCmbKelas();
        initCmbMataKuliah();
        initCmbRuangan();
        initCmbJurusan();
        initValue(jadwal);
        
        a.add(this);
        a.validate();
        a.pack();
        a.setVisible(true);
    }

    public void initCmbHari() {
        cmbHari.removeAllItems();
        cmbHari.addItem("Senin");
        cmbHari.addItem("Selasa");
        cmbHari.addItem("Rabu");
        cmbHari.addItem("Kamis");
        cmbHari.addItem("Jumat");
        cmbHari.addItem("Sabtu");
    }

    public void initCmbDosen() {
        cmbDosen.removeAllItems();
        TblDosenDao dosdao = new TblDosenDao();
        Iterator it = dosdao.getAllDosen().iterator();
        while (it.hasNext()) {
            TblDosen data = (TblDosen) it.next();
            cmbDosen.addItem(data.getNamaDosen());
        }
    }

    public void initCmbKelas() {
        cmbKelas.removeAllItems();
        TblKelasDao klsdao = new TblKelasDao();
        Iterator it = klsdao.getAllKelas().iterator();
        while (it.hasNext()) {
            TblKelas data = (TblKelas) it.next();
            cmbKelas.addItem(data.getKelas());
        }
    }

    public void initCmbMataKuliah() {
        cmbMataKuliah.removeAllItems();
        TblMakulDao mkldao = new TblMakulDao();
        Iterator it = mkldao.getAllMakul().iterator();
        while (it.hasNext()) {
            TblMakul data = (TblMakul) it.next();
            cmbMataKuliah.addItem(data.getMataKuliah());
        }
    }

    public void initCmbRuangan() {
        cmbRuangan.removeAllItems();
        TblRuanganDao ruangdao = new TblRuanganDao();
        Iterator it = ruangdao.getAllRuangan().iterator();
        while (it.hasNext()) {
            TblRuangan data = (TblRuangan) it.next();
            cmbRuangan.addItem(data.getNamaRuangan());
        }
    }

    public void initCmbJurusan() {
        cmbJurusan.removeAllItems();
        TblJurusanDao jrsdao = new TblJurusanDao();
        Iterator it = jrsdao.getAllJurusan().iterator();
        while (it.hasNext()) {
            TblJurusan data = (TblJurusan) it.next();
            cmbJurusan.addItem(data.getJurusan());
        }
    }

    public void initValue(TblJadwal jadwal) {
        this.jadwal = jadwal;
        if (jadwal != null) {
            cmbDosen.setSelectedItem(jadwal.getTblDosen().getNamaDosen());
            cmbHari.setSelectedIndex(jadwal.getHari() - 1);
            cmbKelas.setSelectedItem(jadwal.getTblKelas().getKelas());
            cmbMataKuliah.setSelectedItem(jadwal.getTblMakul().getMataKuliah());
            cmbRuangan.setSelectedItem(jadwal.getTblRuangan().getNamaRuangan());
            cmbJurusan.setSelectedItem(jadwal.getTblJurusan().getJurusan());
            jSpinner1.setValue(jadwal.getJamMulai());
            jSpinner2.setValue(jadwal.getJamSelesai());
//            txtMulai.setText(jadwal.getJamMulai().toString());
//            txtSelesai.setText(jadwal.getJamSelesai().toString());
        } else {
            jSpinner1.setValue(getJam("00:00:00"));
            jSpinner2.setValue(getJam("00:00:00"));
        }
    }

    public Date getJam(String Jam) {
        //String str = "08:03:10 pm";
        DateFormat formatter = new SimpleDateFormat("hh:mm:ss");
        Date date = null;
        try {
            date = (Date) formatter.parse(Jam);
        } catch (ParseException ex) {
            Logger.getLogger(JadwalOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
        return date;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbJurusan = new javax.swing.JComboBox();
        cmbMataKuliah = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbRuangan = new javax.swing.JComboBox();
        cmbKelas = new javax.swing.JComboBox();
        cmbDosen = new javax.swing.JComboBox();
        cmbHari = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner1 = new javax.swing.JSpinner();

        jLabel8.setText("Jurusan");

        jLabel7.setText("Kelas");

        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbMataKuliah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Jam Selesai");

        jLabel6.setText("Ruangan");

        jLabel1.setText("Mata Kuliah");

        cmbRuangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbDosen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbHari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Dosen");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Jam Mulai");

        jLabel3.setText("Hari");

        jSpinner2.setModel(new SpinnerDateModel());
        jSpinner2.setEditor(new JSpinner.DateEditor(jSpinner2, "HH:mm:ss"));

        jSpinner1.setModel(new SpinnerDateModel());
        jSpinner1.setEditor(new JSpinner.DateEditor(jSpinner1, "HH:mm:ss"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbHari, 0, 214, Short.MAX_VALUE)
                            .addComponent(cmbRuangan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDosen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMataKuliah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1)
                            .addComponent(jSpinner2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            TblDosenDao dosdao = new TblDosenDao();
            TblDosen dosen = dosdao.getTblDosByName(cmbDosen.getSelectedItem().toString());

            TblKelasDao klsdao = new TblKelasDao();
            TblKelas kelas = klsdao.getTblKlsByName(cmbKelas.getSelectedItem().toString());

            TblMakulDao mkldao = new TblMakulDao();
            TblMakul makul = (TblMakul) mkldao.getTblMklByName(cmbMataKuliah.getSelectedItem().toString());

            TblRuanganDao ruangdao = new TblRuanganDao();
            TblRuangan ruang = (TblRuangan) ruangdao.getTblRuangByName(cmbRuangan.getSelectedItem().toString());

            TblJurusanDao jrsdao = new TblJurusanDao();
            TblJurusan jurusan = (TblJurusan) jrsdao.getTblJurByName(cmbJurusan.getSelectedItem().toString());

            TblJadwal jad = new TblJadwal();
            jad.setTblDosen(dosen);
            jad.setTblKelas(kelas);
            jad.setTblMakul(makul);
            jad.setTblRuangan(ruang);
            jad.setTblJurusan(jurusan);
            jad.setHari(cmbHari.getSelectedIndex() + 1);

            jad.setJamMulai((Date) jSpinner1.getValue());
            jad.setJamSelesai((Date) jSpinner2.getValue());

            int confirm = JOptionPane.showConfirmDialog(this, "Yakin Data Ini Ingin Disimpan?", "Simpan Data", JOptionPane.OK_CANCEL_OPTION);
            if (confirm == JOptionPane.OK_OPTION) {
                TblJadwalDao jaddao = new TblJadwalDao();
                if (this.jadwal != null) {
                    jad.setIdJadwal(this.jadwal.getIdJadwal());
                    jaddao.updateJadwal(jad);
                    JOptionPane.showMessageDialog(this, "Data Telah Berhasil Diupdate", "Update", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    jaddao.addJadwal(jad);
                    JOptionPane.showMessageDialog(this, "Data Telah Berhasil Diinput", "Insert", JOptionPane.INFORMATION_MESSAGE);
                }
                //makuldao.addMakul(makul);
                //JOptionPane.showMessageDialog(this, "Data Telah Berhasil Diinput", "Insert Makul", JOptionPane.INFORMATION_MESSAGE);
                a.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pastikan Inputan Yang Anda Masukan Benar", "Error", JOptionPane.ERROR_MESSAGE);
        }
//        ManageJadwalGui jadgui = new ManageJadwalGui();
//        jadgui.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDosen;
    private javax.swing.JComboBox cmbHari;
    private javax.swing.JComboBox cmbJurusan;
    private javax.swing.JComboBox cmbKelas;
    private javax.swing.JComboBox cmbMataKuliah;
    private javax.swing.JComboBox cmbRuangan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
