/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ams.gui;

import ams.dao.TblRuanganDao;
import ams.entity.TblRuangan;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Bayu
 */
public class RuanganOperation extends javax.swing.JPanel {

    TblRuangan ruang;
    JDialog a = new JDialog(new FormUtama(),"Manage Mata Kuliah",JDialog.ModalityType.APPLICATION_MODAL);
    public RuanganOperation(TblRuangan ruang) {
        initComponents();
        initCmbLantai();
        initValue(ruang);
        
        a.add(this);
        a.validate();
        a.pack();
        a.setVisible(true);
    }
    
    private void initCmbLantai(){
        cmbLantai.removeAllItems();
        for (int i = 4; i < 8; i++) {
            cmbLantai.addItem(i);
        }
    }
    
    private void initValue(TblRuangan ruang){
        this.ruang = ruang;
        if (ruang != null) {
            txtRuangan.setText(ruang.getNamaRuangan());
            cmbLantai.setSelectedItem(ruang.getLantai());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbLantai = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRuangan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        cmbLantai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Ruangan");

        jLabel2.setText("Lantai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRuangan)
                            .addComponent(cmbLantai, 0, 188, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbLantai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtRuangan.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Pastikan Inputan Yang Anda Masukan Benar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                TblRuangan ruang = new TblRuangan();
                ruang.setNamaRuangan(txtRuangan.getText());
                ruang.setLantai(Integer.parseInt(cmbLantai.getSelectedItem().toString()));

                int confirm = JOptionPane.showConfirmDialog(this, "Yakin Data Ini Ingin Disimpan?", "Simpan Data", JOptionPane.OK_CANCEL_OPTION);
                if (confirm == JOptionPane.OK_OPTION) {
                    TblRuanganDao ruangdao = new TblRuanganDao();
                    if (this.ruang != null) {
                        ruang.setIdRuangan(this.ruang.getIdRuangan());
                        ruangdao.updateRuangan(ruang);
                        JOptionPane.showMessageDialog(this, "Data Telah Berhasil Diupdate", "Update", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        ruangdao.addRuangan(ruang);
                        JOptionPane.showMessageDialog(this, "Data Telah Berhasil Diinput", "Insert", JOptionPane.INFORMATION_MESSAGE);
                    }
                    //makuldao.addMakul(makul);
                    //JOptionPane.showMessageDialog(this, "Data Telah Berhasil Diinput", "Insert Makul", JOptionPane.INFORMATION_MESSAGE);
                    a.dispose();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pastikan Inputan Yang Anda Masukan Benar", "Error", JOptionPane.ERROR_MESSAGE);
        }
//        ManageRuanganGui ruanggui = new ManageRuanganGui();
//        ruanggui.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbLantai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtRuangan;
    // End of variables declaration//GEN-END:variables
}
